MAX_VALIDATION_COMMAND_PARTS = 64
MAX_VALIDATION_COMMAND_PART_CHARS = 1000
MAX_VALIDATION_COMMAND_CHARS = 4000
MAX_VALIDATION_EXECUTIONS = 20
MAX_DELEGATION_DEPTH = 1
DEFAULT_MAX_CONCURRENT_DELEGATIONS = 3
DEFAULT_MAX_DELEGATIONS_PER_PARENT_RUN = 6
